#include "API_2.h"




void API_2::drawRect(Integer x, Integer y, Integer l, Integer w, Integer a)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:0000000000000885 begin
{
}
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:0000000000000885 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void API_2::drawExagon(Integer x, Integer y, Integer r, Integer a)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:000000000000088C begin
{
}
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:000000000000088C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void API_2::drawCircle(Integer x, Integer y, Integer r)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:0000000000000892 begin
{
}
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:0000000000000892 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
