#include "API_3.h"




void API_3::rectangle(Integer x, Integer y, Integer l, Integer w, Integer a)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:0000000000000898 begin
{
}
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:0000000000000898 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void API_3::exagon(Integer x, Integer y, Integer r, Integer a)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:000000000000089F begin
{
}
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:000000000000089F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void API_3::circle(Integer x, Integer y, Integer r)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:00000000000008A5 begin
{
}
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:00000000000008A5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
