#include "API_1.h"




void API_1::orientedRectangle(Integer x, Integer y, Integer l, Integer w, Integer a)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:000000000000086C begin
{
}
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:000000000000086C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void API_1::orientedExagon(Integer x, Integer y, Integer r, Integer a)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:0000000000000873 begin
{
}
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:0000000000000873 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void API_1::simpleCircle(Integer x, Integer y, Integer r)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:000000000000087B begin
{
}
// section 127-0-1-1--3720088f:14bfe78bb4e:-8000:000000000000087B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
